apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: root

  source:
    repoURL: {{ .Values.platform.source.repoURL | quote }}
    targetRevision: {{ .Values.platform.source.targetRevision | default "main" | quote }}
    path: {{ .Values.platform.source.path }}
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      namespace: argocd
      jsonPointers:
        - /spec/syncPolicy/automated
        - /spec/source/targetRevision

  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
