apiVersion: v2
name: argo-cd
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool for Kubernetes.
version: 1.0.1
dependencies:
  - name: argo-cd
    version: 9.1.4
    repository: https://argoproj.github.io/argo-helm
