apiVersion: v2
name: argo-cd
description: Deploys Argo CD and core Argo CD resources for our internal developer platform.
version: 1.0.2
dependencies:
  - name: argo-cd
    version: 9.1.4
    repository: https://argoproj.github.io/argo-helm
