apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.platform.tenantProject.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  description: Project for namespace-scoped resources provisioned for each tenant.
  sourceRepos:
  {{- range .Values.platform.repos }}
    - {{ . | quote }}
  {{- end }}
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
